RoomBooking.Web/Models/ErrorViewModel.cs
namespace RoomBooking.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RoomBooking.Web/ViewModels/BookingsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using RoomBooking.Core.Entities;
using RoomBooking.Web.DataTransferObjects;
using RoomBooking.Web.Validations;

namespace RoomBooking.Web.ViewModels
{
    public class BookingsViewModel
    {
        public int Id { get; set; }

        public int CustomerId { get; set; }
        public IEnumerable<CustomerDto> Customers { get; set; }
        public int RoomId { get; set; }
        public IEnumerable<Room> Rooms { get; set; }

        [RegularExpression("^(0[8-9]|1[0-7]:[0-5][0-9])|18:00$", ErrorMessage = "Zeit muss zwischen 08:00 und 18:00 liegen")]
        [CorrectTimes]
        //[Remote("CheckTimeBeetween8And18", "Bookings", HttpMethod = "POST", ErrorMessage = "Time has to be beetween 08:00 and 18:00")]
        [Required]
        public String From { get; set; }

        [RegularExpression("^(0[8-9]|1[0-7]:[0-5][0-9])|18:00$", ErrorMessage = "Zeit muss zwischen 08:00 und 18:00 liegen")]
        [CorrectTimes]
        [Required]
        public String To { get; set; }

    }
}

RoomBooking.Web/ViewModels/HomeIndexViewModel.cs
using System.Collections.Generic;
using RoomBooking.Core.Entities;
using RoomBooking.Web.DataTransferObjects;

namespace RoomBooking.Web.ViewModels
{
    public class HomeIndexViewModel
    {
        public HomeIndexViewModel()
        {
        }

        public HomeIndexViewModel(List<Customer> customers, int customerId, List<Booking> bookings) 
        {
            Customers = new List<CustomerDto>();
            foreach (var customer in customers)
            {
                Customers.Add(new CustomerDto(customer));
            }
            CustomerId = customerId;
            Bookings = bookings;
        }

        public List<CustomerDto> Customers { get; set; }  // Customers in der Combobox
        public IEnumerable<Booking> Bookings { get; set; }    // Buchungen des ausgewählten Customers

        public int CustomerId { get; set; }

    }
}

RoomBooking.Web/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RoomBooking.Core.Contracts;
using RoomBooking.Web.DataTransferObjects;
using RoomBooking.Web.ViewModels;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RoomBooking.Web.Controllers
{
  public class BookingsController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;

    public BookingsController(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
      return RedirectToAction("Index", "Home");
    }


    /// <summary>
    /// Anforderung der Bearbeitung einer Buchung
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<ActionResult> Edit(int id)
    {
      var booking = await _unitOfWork.Bookings.GetByIdAsync(id);

      if (booking == null)
      {
        return NotFound();
      }

      var viewModel = new BookingsViewModel()
      {
        Id = booking.Id,
        From = booking.From,
        To = booking.To,
        CustomerId = booking.Customer.Id,
        RoomId = booking.Room.Id,
        Customers = (await _unitOfWork.Customers.GetAllAsync()).Select(c => new CustomerDto(c)),
        Rooms = await _unitOfWork.Rooms.GetAllAsync()
      };

      return View("Edit", viewModel);
    }

    /// <summary>
    /// ViewModel auf Korrektheit überprüfen und abspeichern
    /// </summary>
    /// <param name="viewModel"></param>
    /// <returns>Ergebnis des Update als Response</returns>
    [HttpPost]
    public async Task<ActionResult> Edit(BookingsViewModel viewModel)
    {
      var customers = (await _unitOfWork.Customers.GetAllAsync()).Select(c => new CustomerDto(c));
      var rooms = await _unitOfWork.Rooms.GetAllAsync();
      viewModel.Customers = customers;
      viewModel.Rooms = rooms;
      if (ModelState.IsValid)
      {
        var booking = await _unitOfWork.Bookings.GetByIdAsync(viewModel.Id);
        if (booking == null)
        {
          return NotFound();
        }
        booking.From = viewModel.From;
        booking.To = viewModel.To;
        booking.CustomerId = viewModel.CustomerId;
        booking.RoomId = viewModel.RoomId;
        try
        {
          await _unitOfWork.SaveAsync();
          return RedirectToAction("Index", "Home", new { id = booking.CustomerId });
        }
        catch (ValidationException validationException)
        {
          // Beim Speichern wurde geprüft, ob die zu speichernde Buchung sich nicht mit
          // anderen Buchungen des Raums überlagert
          ModelState.AddModelError((string)validationException.Value, validationException.Message);
          return View("Edit", viewModel);
        }
        catch (Exception exception)
        {
          ModelState.AddModelError("", exception.GetType() + " " + exception.Message);
          return View("Edit", viewModel);
        }
      }
      return View("Edit", viewModel);

    }


    /// <summary>
    /// Buchung löschen und auf Hauptseite weiter verweisen.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<ActionResult> Delete(int id)
    {
      var booking = await _unitOfWork.Bookings.GetByIdAsync(id);
      if (booking == null)
      {
        return NotFound();
      }
      var customerId = booking.CustomerId;
      _unitOfWork.Bookings.Delete(booking);
      await _unitOfWork.SaveAsync();
      return RedirectToAction("Index", "Home", new { id = customerId });
    }

    [AllowAnonymous]
    [HttpPost]
    public ActionResult CheckTimeBeetween8And18(string from)
    {
      bool ok = DateTime.TryParse(from, out DateTime fromTime);
      if (!ok)
      {
        return Json(false);
      }
      return Json(fromTime >= DateTime.Parse("08:00")
          && fromTime <= DateTime.Parse("18:00"));
    }

  }
}

RoomBooking.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RoomBooking.Core.Contracts;
using RoomBooking.Core.Entities;
using RoomBooking.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RoomBooking.Web.Controllers
{
  public class HomeController : Controller
  {
    private readonly IUnitOfWork _unitOfWork;

    public HomeController(IUnitOfWork unitOfWork)
    {
      _unitOfWork = unitOfWork;
    }


    public async Task<ActionResult> Index(int? id)
    {
      var customers = (await _unitOfWork.Customers.GetAllAsync()).ToList();
      List<Booking> bookings;
      Customer customer;
      int customerId;
      if (id != null)
      {
        customer = customers.Single(c => c.Id == id);
      }
      else
      {
        customer = customers.FirstOrDefault();
      }
      if (customer != null)
      {
        customerId = customer.Id;
        bookings = (await _unitOfWork.Bookings.GetAllWithRoomsAsync(customerId)).ToList();
      }
      else
      {
        customerId = 0;
        bookings = new List<Booking>();
      }
      var homeIndexViewModel = new HomeIndexViewModel(customers, customerId, bookings);
      return View(homeIndexViewModel);
    }

    [HttpPost]
    public async Task<ActionResult> Index(HomeIndexViewModel viewModel)
    {
      int customerId = viewModel.CustomerId;
      var customers = (await _unitOfWork.Customers.GetAllAsync()).ToList();
      var bookings = (await _unitOfWork.Bookings.GetAllWithRoomsAsync(customerId)).ToList();
      var homeIndexViewModel = new HomeIndexViewModel(customers, customerId, bookings);
      return View(homeIndexViewModel);
    }

    public IActionResult Error()
    {
      return View();
    }
  }
}

RoomBooking.Web/Views/Bookings/Edit.cshtml
@model RoomBooking.Web.ViewModels.BookingsViewModel

@{
    ViewBag.Title = "Edit booking";
}

<h2>Edit booking</h2>

<form method="post" asp-controller="Bookings" asp-action="Edit">
    <input asp-for="Id" type="hidden" />
    <div class="form-group">
        <label asp-for="RoomId">Room</label>
        <div>
            <select asp-for="RoomId" class="form-control">
                @foreach (var room in Model.Rooms)
            {
                    <option value=@room.Id>@room.RoomNumber</option>
                }
            </select>
        </div>
        <span asp-validation-for="RoomId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CustomerId">Customer</label>
        <div>
            <select asp-for="CustomerId" class="form-control">
                @foreach (var customer in Model.Customers)
            {
                    <option value=@customer.Id>@customer.Name</option>
                }
            </select>
        </div>
        <span asp-validation-for="CustomerId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="From">From</label>
        <input asp-for="From" class="form-control" />
        <span asp-validation-for="From" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="To">To</label>
        <input asp-for="To" class="form-control" />
        <span asp-validation-for="To" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
@section Scripts {
    <script></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

RoomBooking.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

RoomBooking.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RoomBooking.Web/Views/Home/Index.cshtml
@model RoomBooking.Web.ViewModels.HomeIndexViewModel
@{
    ViewBag.Title = "Room Booking";
}

<h2>@ViewBag.Message</h2>


<form method="post" asp-controller="Home" asp-action="Index">
    <div class="form-group">
        Customer:
        <select asp-for="CustomerId">
            @foreach (var customer in Model.Customers)
            {
                <option value=@customer.Id>@customer.Name</option>
            }
        </select>
        <button type="submit" class="btn btn-primary">Reload</button>
    </div>
    <hr/>


    @*<div id="divBookingList">
        @Html.Partial("_BookingList", Model.Bookings)
    </div>*@
    
    <div class="row">
        <div class="col-md-6">

            <table class="table table-striped">
                <tr>
                    <th class="col-md-2">
                        Roomnumber
                    </th>
                    <th class="col-md-2">
                        From
                    </th>
                    <th class="col-md-2">
                        To
                    </th>
                    <th class="col-md-2">
                    </th>
                </tr>

                @foreach (var booking in Model.Bookings)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => booking.Room.RoomNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => booking.From)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => booking.To)
                        </td>
                        <td >
                            <a href="@Url.Action("Edit", "Bookings", new {id = booking.Id})">
                                Edit
                            </a> |
                            <a href="@Url.Action("Delete", "Bookings", new {id = booking.Id})">
                                Delete
                            </a>
                        </td>

                    </tr>
                }

            </table>
        </div>
    </div>

</form>

RoomBooking.Web/Views/Home/_BookingList.cshtml
@model IEnumerable<RoomBooking.Core.Entities.Booking>

<div class="row">
    <div class="col-md-6">

        <table class="table table-striped">
            <tr>
                <th class="col-md-2">
                    Roomnumber
                </th>
                <th class="col-md-2">
                    From
                </th>
                <th class="col-md-2">
                    To
                </th>
                <th class="col-md-2">
                </th>
            </tr>

            @foreach (var booking in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => booking.Room.RoomNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => booking.From)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => booking.To)
                    </td>
                    <td >
                        <a href="@Url.Action("Edit", "Bookings", new {id = booking.Id})">
                            Edit
                        </a> |
                        <a href="@Url.Action("Delete", "Bookings", new {id = booking.Id})">
                            Delete
                        </a>
                    </td>

                </tr>
            }

        </table>
    </div>
</div>

RoomBooking.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoomBooking.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RoomBooking.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RoomBooking.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>